# Generated by Django 5.0.4 on 2024-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/media/profile_pictures/frank.svg', upload_to='profile/'),
        ),
    ]
